### ISSUE TITLE
hi,我在用的过程中出现了这个错误

### ISSUE THREAD

**Issue by jeremy16601** [morrislaptop/vue-web3#1]
`ERROR in ./node_modules/vue-web3/dist/vue-web3.esm.js`
`Module not found: Error: Can't resolve 'web3' in 'D:\nodejs-Project\EtherDice_Web\node_modules\vue-web3\dist'`
` @ ./node_modules/vue-web3/dist/vue-web3.esm.js 1:6-21`
` @ ./src/main.js`
` @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main`
麻烦帮忙看下吧，谢谢

**Comment by morrislaptop** [comment]
Npm add web3
