### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jeremy16601** [morrislaptop/vue-web3#2]
ERROR in ./node_modules/web3/packages/web3-utils/src/utils.js
Module not found: Error: Can't resolve 'eth-lib/src/hash' in '/Users/xueqingli/Documents/node.js项目/EtherDice_Web/node_modules/web3/packages/web3-utils/src'
 @ ./node_modules/web3/packages/web3-utils/src/utils.js 27:11-38
 @ ./node_modules/web3/packages/web3-utils/src/index.js
 @ ./node_modules/web3/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./node_modules/web3/packages/web3-utils/src/index.js
Module not found: Error: Can't resolve 'ethjs-unit' in '/Users/xueqingli/Documents/node.js项目/EtherDice_Web/node_modules/web3/packages/web3-utils/src'
 @ ./node_modules/web3/packages/web3-utils/src/index.js 26:16-37
 @ ./node_modules/web3/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./node_modules/web3/packages/web3-utils/src/index.js
Module not found: Error: Can't resolve 'randomhex' in '/Users/xueqingli/Documents/node.js项目/EtherDice_Web/node_modules/web3/packages/web3-utils/src'
 @ ./node_modules/web3/packages/web3-utils/src/index.js 29:16-36
 @ ./node_modules/web3/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

**Comment by morrislaptop** [comment]
Something weird going on with dependencies - released 2.0.0 with no dependencies which relies on the main project supplying the web3 instance (which is probably better in the long run)
