### ISSUE TITLE
fyi issue with web3 beta 34 and 35

### ISSUE THREAD

**Issue by paolodina** [morrislaptop/vue-web3#3]
Configuring subscriptions I got this error:

`WebSocket connection to 'wss://ropsten.infura.io/ws' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
`

As [described here](https://infura.io/docs/wss/introduction), it's [an issue](https://github.com/ethereum/web3.js/issues/1559) in web3 beta34/35, so stick on 33 or use the 1.0 branch.

**Comment by morrislaptop** [comment]
Thanks
